/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.apache.spark.sql.SparkSession


object App {
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder.appName("Divy Application").getOrCreate()
    val divyData = spark.read.option("inferSchema", "true").option("header", "true").csv("/Users/billy/Desktop/Divvy_Trips.csv")
    divyData.show(5, false)
    spark.stop()
  }
}
